name: Last Updated Timestamp
on:
  workflow_run:
    workflows: ["Response Time CI"]
    types:
      - completed

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install yq
        run: sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && sudo chmod +x /usr/bin/yq

      - name: Replace timestamp for last update
        run: |
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          echo "‚è±Ô∏è Generated timestamp: $timestamp"
          sed -i "s/LAST_UPDATE_TIMESTAMP/$timestamp/g" .upptimerc.yml

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '.upptimerc.yml'
          message: 'üîÑ Update last update timestamp'
          default_author: github_actions